Importing libraries and loading dataset

In [3]:
from pathlib import Path
import pandas as pd
import numpy as np

DATA_PATH = Path("../data/raw/Motor vehicle insurance data.csv")

df = pd.read_csv(DATA_PATH, sep = ';')

df_fe = df.copy()

In [28]:
df_fe.head()

,ID,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Distribution_channel,Seniority,Policies_in_force,Max_policies,...,Cylinder_capacity,Value_vehicle,N_doors,Type_fuel,Length,Weight,Customer_Age,Driving_Experience,Customer_Tenure,Vehicle_Age
0,1,2015-05-11,2015-05-11,2016-05-11,1956-04-15,1976-03-20,0,4,1,2,...,599,7068.0,0,P,NaN,190,62,42,3.0,48
1,1,2015-05-11,2016-05-11,2017-05-11,1956-04-15,1976-03-20,0,4,1,2,...,599,7068.0,0,P,NaN,190,62,42,3.0,48
2,1,2015-05-11,2017-05-11,2018-05-11,1956-04-15,1976-03-20,0,4,2,2,...,599,7068.0,0,P,NaN,190,62,42,3.0,48
3,1,2015-05-11,2018-05-11,2019-05-11,1956-04-15,1976-03-20,0,4,2,2,...,599,7068.0,0,P,NaN,190,62,42,3.0,48
4,2,NaT,NaT,NaT,1956-04-15,1976-03-20,0,4,2,2,...,599,7068.0,0,P,NaN,190,62,42,NaN,48

In [18]:
df_fe[
    ["Date_start_contract","Date_last_renewal","Date_next_renewal","Date_birth","Date_driving_licence","Date_lapse","Year_matriculation" ]
].head()

,Date_start_contract,Date_last_renewal,Date_next_renewal,Date_birth,Date_driving_licence,Date_lapse,Year_matriculation
0,2015-05-11,2015-05-11,2016-05-11,1956-04-15,1976-03-20,NaT,2004
1,2015-05-11,2016-05-11,2017-05-11,1956-04-15,1976-03-20,NaT,2004
2,2015-05-11,2017-05-11,2018-05-11,1956-04-15,1976-03-20,NaT,2004
3,2015-05-11,2018-05-11,2019-05-11,1956-04-15,1976-03-20,NaT,2004
4,NaT,NaT,NaT,1956-04-15,1976-03-20,NaT,2004

In [19]:
date_coloumns = ["Date_start_contract","Date_last_renewal","Date_next_renewal","Date_birth","Date_driving_licence","Date_lapse","Year_matriculation"]

In [20]:
#Converting Dates
for col in date_coloumns:
    df_fe[col] = pd.to_datetime(df_fe[col],errors='coerce')

In [21]:
#Customers Age
Reference_year = 2018
df_fe["Customer_Age"] = (Reference_year - df_fe['Date_birth'].dt.year)

In [22]:
#Driving Experience
df_fe["Driving_Experience"] = (Reference_year - df_fe['Date_driving_licence'].dt.year)

In [23]:
#Customer Tenure
df_fe["Customer_Tenure"] = (Reference_year - df_fe['Date_start_contract'].dt.year)

In [27]:
#Vehicle Age
df_fe["Vehicle_Age"] = (Reference_year - df_fe["Year_matriculation"].dt.year)

In [29]:
#claim frequency
df_fe["Claim_per_year"] = df_fe["N_claims_year"] / df_fe["Seniority"]